IdoSagiv/CommuniDog

- README.md
I've added some changed to your README.md file.
The most important change is about Android Virtual Device - in order to explain the user what are the options for using the app and to referred him the relevant links how to use virtual device.
Also I've added some changes about what is a valid ID.
> Readme suggestion - Tal Yichye

- app/src/main/java/communi/dog/aplicatiion/DB.java
- app/src/main/java/communi/dog/aplicatiion/ProfilePage.java
- app/src/main/res/layout/activity_profile_page.xml
to add this button i added a button in activity_profile_page.xml
then added a method logout in ProfilePage.java
and lastly a resetUser method in DB.java
> added logout button to user profile

- app/src/main/java/communi/dog/aplicatiion/CommuniDogApp.java
- app/src/main/java/communi/dog/aplicatiion/DB.java
- app/src/main/java/communi/dog/aplicatiion/MapState.java
Closes #20 
add SharedPreferences to db, and save current location to it
> Issue20-Save current location per user 

- app/src/main/java/communi/dog/aplicatiion/AddMarkerActivity.java
- app/src/main/java/communi/dog/aplicatiion/DB.java
- app/src/main/java/communi/dog/aplicatiion/LoginActivity.java
- app/src/main/java/communi/dog/aplicatiion/MapHandler.java
- app/src/main/java/communi/dog/aplicatiion/MapScreenActivity.java
- app/src/main/java/communi/dog/aplicatiion/MapState.java
- app/src/main/java/communi/dog/aplicatiion/MarkerDescriptor.java
- app/src/main/java/communi/dog/aplicatiion/ProfilePageActivity.java
Now the map will be update when ever the data is changes (by the current user, by other users or manually from the DB)
Closes #33
> Async update map

- .idea/misc.xml
- app/src/main/java/communi/dog/aplicatiion/ProfilePageActivity.java
- app/src/main/java/communi/dog/aplicatiion/RequestAccessActivity.java
- app/src/main/res/layout/activity_get_access.xml
closes #41
a new activity xml file is added which contatin edit text for entering the access code, and two buttons: one for registation and for requesting a new access code.
moreover, a new class for this activity is added.
> add activity for entering acess code

- .idea/misc.xml
- app/src/main/java/communi/dog/aplicatiion/ProfilePageActivity.java
- app/src/main/java/communi/dog/aplicatiion/RequestAccessActivity.java
- app/src/main/res/layout/activity_get_access.xml
closes #43
if the user enters the default password - he is now referenced to the registration page as before.
if the user requests for access code - an email pop-up pops and the user can enter his email
> default access code is allowed and email popup is presented when requesting access code

- app/src/main/java/communi/dog/aplicatiion/DB.java
- app/src/main/java/communi/dog/aplicatiion/LoginActivity.java
now when userId or password is incorrect, the user gets an informative message about why authentication failed.
will improve user experience (UX).
> issue 51 (bug) is fixed

- app/src/main/res/layout/activity_register.xml
now can scroll the registarion fields so all of the screen is reachable
> issue 52 fixed

- app/src/main/AndroidManifest.xml
- app/src/main/java/communi/dog/aplicatiion/AboutPage.java
- app/src/main/java/communi/dog/aplicatiion/MapScreenActivity.java
- app/src/main/res/layout/activity_about_section.xml
- app/src/main/res/menu/info_menu_bar.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Added an about section (in menu), solved issue #63 
I made it a pop-up window (it look nicer in my opinion)
* ![image](https://user-images.githubusercontent.com/49747014/122655385-9a3ec980-d15a-11eb-9fbb-3368c483215d.png)
* ![image](https://user-images.githubusercontent.com/49747014/122655401-af1b5d00-d15a-11eb-8e67-34cbebc045b4.png)
> Added an about section (in menu) issue #63

- app/src/main/java/communi/dog/aplicatiion/MapScreenActivity.java
> when rotating screen, keep the more info's drawer state

- .idea/misc.xml
- app/build.gradle
- app/src/main/java/communi/dog/aplicatiion/DB.java
- app/src/main/java/communi/dog/aplicatiion/LoginActivity.java
- app/src/main/java/communi/dog/aplicatiion/MainActivity.java
- app/src/main/java/communi/dog/aplicatiion/MapState.java
- app/src/main/java/communi/dog/aplicatiion/MarkerDescriptor.java
- app/src/main/java/communi/dog/aplicatiion/ProfilePageActivity.java
- app/src/main/java/communi/dog/aplicatiion/RegisterActivity.java
- app/src/main/java/communi/dog/aplicatiion/User.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/wait_screen.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/communi/dog/aplicatiion/LoginActivityTest.java
> Autentication issue

- .idea/.name
- .idea/misc.xml
- app/src/main/java/communi/dog/aplicatiion/LoginActivity.java
- app/src/main/java/communi/dog/aplicatiion/MapScreenActivity.java
when a user is logged in - if he is approved -> navigate to mapscreen acitivity
else -> navigate to waits screen until he gets approved.
when a manager logs in he sees a notifictions button where he can aprove users
> in app navigation

- app/src/main/res/layout/activity_register.xml
Fixed bug #90
Removed the unneccesry scrollview and now to code build successfully.
> Fixed bug #90

- app/src/main/java/communi/dog/aplicatiion/MarkerDescriptor.java
the saved fields name in the DB didn't match the one in the code so when reading from DB the fields got the default value which is false
Closes #97
> change fields name to fit FireBase version

- .idea/misc.xml
- app/build.gradle
- app/src/main/java/communi/dog/aplicatiion/LoginActivity.java
- app/src/main/java/communi/dog/aplicatiion/MapScreenActivity.java
> Fixed app crashed at the first login

- app/src/main/res/layout/activity_about_section.xml
- app/src/main/res/values/strings.xml
Fixed issue #79.
The problem was that if there is not enogh space to display all the info in the "About" screen than is would cutout and you can't scroll down to see.
Fixed it by addition of option to scroll down and see it (the info).
> Fixed issue #79

- app/src/main/java/communi/dog/aplicatiion/RegisterActivity.java
Added a function 'onBackPressed'.
> Fixed moving back from the register page

- app/src/main/java/communi/dog/aplicatiion/LoginActivity.java
Set the login button to disable at the begiging.
> Fixed login button

- .idea/misc.xml
- app/src/main/res/drawable/ic_baseline_exit.xml
- app/src/main/res/layout/activity_profile_page.xml
made the logout buttin user friendly and understanable.
before that change there was an x image with no explenation, the user could not know that this is the logout button.
now this is clear and understanable.
> Logout update profile page

- app/src/main/java/communi/dog/aplicatiion/ProfilePageActivity.java
When fixed the following bug https://github.com/IdoSagiv/CommuniDog/issues/67, the PR https://github.com/IdoSagiv/CommuniDog/pull/95 was with wrong comment.
Fixed the wrong comment in this PR.
> Fixed wrong comment

- app/src/main/java/communi/dog/aplicatiion/MapScreenActivity.java
- app/src/main/res/menu/info_menu_bar.xml
added a logout button in the info sliding menu for more comfortable use for the user.
> Logout in info menu

- app/src/main/java/communi/dog/aplicatiion/LoginActivity.java
- app/src/main/java/communi/dog/aplicatiion/RegisterActivity.java
email - up to 254
name - from 3 to 64
password - more than 6
note: the ranges were chosen from multiple reliable websites
> limit the input length in the register and login pages.

- app/src/main/res/menu/info_menu_bar.xml
fixed this bug, now after a click, the buttin stops being clicked.
> bug fixed - info menu stays clicked after clicking.
